# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: thunderdome-planning-poker
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env: [ CGO_ENABLED=0 ]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
universal_binaries:
  - replace: true
dockers:
  - image_templates:
      - "sharrnah/{{.ProjectName}}:{{ .Tag }}-amd64"
      - "sharrnah/{{.ProjectName}}:latest-amd64"
    dockerfile: "build/gorDockerfile"
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/Sharrnah/{{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/Sharrnah/{{.ProjectName}}
  - image_templates:
      - "sharrnah/{{.ProjectName}}:{{ .Tag }}-arm64v8"
      - "sharrnah/{{.ProjectName}}:latest-arm64v8"
    goarch: arm64
    dockerfile: "build/gorDockerfile"
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/Sharrnah/{{.ProjectName}}
      - --label=org.opencontainers.image.source=https://github.com/Sharrnah/{{.ProjectName}}
docker_manifests:
  - name_template: sharrnah/{{.ProjectName}}:latest
    image_templates:
      - sharrnah/{{.ProjectName}}:latest-amd64
      - sharrnah/{{.ProjectName}}:latest-arm64v8
  - name_template: sharrnah/{{.ProjectName}}:{{ .Tag }}
    image_templates:
      - sharrnah/{{.ProjectName}}:{{ .Tag }}-amd64
      - sharrnah/{{.ProjectName}}:{{ .Tag }}-arm64v8
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dist: release
